package GenericUtilities;

/**
 * @Description: used to store Endpoint of all the APIs
 */

public interface EndPoint {
	
	
    String CREATELEAD = "/applicationlayer/v1/term-case/application";
    String CREATEUNIFIEDLEAD="/unified/lead";
    String SAVEBANKDETAIL = "/unified/caseapplication/{case_code}/bankaccount";
    String GETALLDATA = "/unified/caseapplication/{case_code}/all";
    String EXPERIAN = "/experian/v1/bureau/experian/demog";
    String UNIFIEDLEADPOST = "/unified/lead";
    String UNIFIEDALL = "/unified/caseapplication/{case_code}/all";
    String UNIFIEDLEADPUT = "/applicationlayer/v1/term-case/application/";
    String GETSUMMARYAPI = "/partner/summary/{case_code}";
    String GETEXPERIAN = "/experian/v1/bureau/experian/demog/{mobile_no}";
    String GETEXPERIAN1 = "/experian/v1/bureau/experian/demog";
    String NSDL_service ="/app-bank/v1/nsdl/initiate";
    String PANBASE64 = "/livelinessservice/kyc/s3/data/{case_code}";
    String SAVESELFIE = "/livelinessservice/selfie/save";
    String UPDATESELFIE = "/livelinessservice/selfie/save";
    String SAVEPARTNEROFFER = "/partner/offer";
    String caseSTATUS = "/unified/caseapplication/{case_code}/status";
    String OFFERCREATION = "/offers/v1/case-application/{case_code}/case/offers/";
    String SAVEPAYOUT = "/unified/caseapplication/{case_code}/payout";
    String REDIRECTLINK = "/partner/redirectlink";
    String UNIFIEDSTATUS = "/unified/caseapplication/{case_code}/status";
    String INITIATEVCIP = "/vcip/v2/case-application/applicant/{case_code}/init?identifier={mobile_no}";
    String GETVCIPSTATUS = "/vcip/v2/case-application/applicant/{case_code}/status?identifier={mobile_no}";
    String RESETVCPIPSTATUS = "/vcip/v2/case-application/applicant/{case_code}/reset?identifier={mobile_no}";
    String SUMMARY = "/partner/summary/{case_code}";
    String GETACCOUNTTYPE = "/partner/bank/account/type?caseCode={case_code}&docCode={docCode}";
    String TRIGGERMAIL = "/partner/email/trigger";
    String GETFLOWDETAILS = "/partner/god/{code}";
    String APPLICATIONFORMSERVICES = "/prefill/v1/application/form";
    String APPLICATIONFORMSERVICES_COAPPLICATIONFORM = "/prefill/v1/coApplication/form";
    String APPLICATIONFORMSERVICES_FATCA = "/prefill/v1/fatca/form";
    String CIBIL= "/coredatalayer/data-connectors/v1/bureau/vendors/transUnion";
    String GETTOPUP = "/topup/{case_code}";
    String TOPUP_RENEWAL = "/topup/renewal/{case_code}";
    String TOPUP_caseINFO = "/topup/case_info/{case_code}";
    String TOPUP_COMPARATIVEANALYSIS = "/topup/comparativeAnalysis/{leadCode}";
    String NACH_CREATEEMANDATE = "/emandateflow/e-mandate/create/eMandate";
    String NACH_CALLBACKEMANDATE = "/emandateflow/e-mandate/callback-eMandate";
    String NACH_CALLBACKSTATUS = "/emandateflow/e-mandate/callback-status";
    String EKYC_FUZZY = "/ekyc/v1/fuzzy";
    String EKYC_HEALTH = "/ekyc/v1/health";
    String DISBURSAL_DETAIL = "/partner/case/disbursal-details?page=1&limit=3";
    String C2W_CREATEDOCUMENT = "/c2w/document/create";
    String C2W_SEND = "/psc/v2/sanction/{caseCode}/send";
    String C2W_FETCHDOCUMENT = "/c2w/document/fetch";
    String C2W_DOCUMENTSIGN = "/c2w/document/sign";
    String C2W_MERGEDOCUMENT = "/c2w/document/merge";
    String PHONE_CHECK_TRUID = "/partner/phonecheck";
    String OTP_SESSION = "/partner/otp/session";
    String UTILITY_GETPARTNER = "/utility/partners";
    String UTILITY_GETIPSCORE = "/utility/lpScore";
    String UTILITY_GETNEGATIVEPINCODE = "/utility/negative-pincode/{case_code}";
    String UTILITY_GET_TOXIC_PINCODE = "/utility/toxicPincode/{pincode_no}";
    String UTILITY_GET_EXPERIMENT_NAMES = "/utility/getexperimentnames";
    String UTILITY_GET_case_ELIGIBLE_COLENDER = "/utility/case_eligible_colender";
    String UTILITY_GET_AUTO_CLOSE = "/utility/autoclose";
    String UTILITY_GET_REDUCING = "/utility/reducing-rate";
    String UTILITY_POST_case_ELIGIBLE_COLENDER = "/utility/case_eligible_colender";
    String UTILITY_caseCOLENDINGPARTNER = "/utility/case_colending_partner";
    String UTILITY_EXPERIMENTLOG = "/utility/case/{case_code}/experimentLog";
    String UTILITY_PARTNERPERFORMANCE = "/utility/partnerPerformance/dataType/{partner_code}";
    String CKYC_HEALTHCHECK = "/ckyc/uptime";
    String CKYC_SEARCHONE = "/ckyc/v1/ckyc/{pan_no}";
    String CKYC_POSTREGISTER = "/ckyc/v1/ckyc";
    String CKYC_POSTSEARCH = "/ckyc/v1/ckyc/search";
    String CKYC_POSTEVENTIFYCKYC = "/ckyc/eventify-ckyc";
    String FLEXIPAY_PAYMENTLINKGENERATED = "/flexipay/v1/initiate/razorpay/payment";
    String FLEXIPAY_PAYMENTDATAFETCHED = "/flexipay/v1/payment_data/{case_code}/link/{payment_code}";
    String AGENCYSERVICE_BITLY = "/agency/v1/bitly";
    String AGENCYSERVICE_ECOMORDERTRACKING = "/agency/v1/ecom/task/order/tracking";
    String DOCUMENTCLASIFICATION_GETSTATUS = "/documentclassification/v1/status";
    String DOCUMENTPREFILL_HEALTHCHECK = "/documentprefill/";
    String DOCUMENTPREFILL_DOCUMENTGENERATE = "/documentprefill/v1/document/generate";
    String DOCUMENTPREFILL_DATACREATION = "/psc/case/{case_code}/kfs";
    String POLICY = "/policy/check-policies/{case_code}";
    String ATTACHEDPOLICY = "/policy/attached-policies/";
    String SHARELEAD_MILESTONES="/milestone/v1/case-application/{case_code}/milestones/{milestone_code}";
    String UPDATEFIELD ="/applicationstatus/api/updateField";
    String GET_CHECKPOINT = "/state/v1/case/{case_code}";
	String ONEPAGECRM_ASSIGNRM="/onepagecrm/assign-rm";
	String ONEPAGECRM_FETCHRM="/onepagecrm/fetchRM";
	String ONEPAGECRM_POSDETAIL="onepagecrm/posdetails/{case_code}";
	String ONEPAGECRM_GETCRMAGENT="/onepagecrm/getCrmAgent/{case_code}";
	String ONEPAGECRM_QUESTIONPRIORITY="/onepagecrm/questionPriority/{case_code}";
    String ONEPAGECRM_APPLICATIONVALIDCHECK = "/onepagecrm/application/validCheck";
    String PENNYDROP = "/api/pennydrop/";
    String ONEPAGECRM_INDUSTRYCLASSIFICATION = "/onepagecrm/{case_code}/industryclassification";
    String ONEPAGECRM_GETACTIVITY = "/onepagecrm/getactivity";
    String ONEPAGECRM_GETREMARK = "/onepagecrm/getremarksv2";
    String ONEPAGECRM_PRODUCTCATEGORY = "/onepagecrm/productcategory";
    String ONEPAGECRM_POSTEXTERNALREMARK = "/onepagecrm/postexternalremarks";
    String ONEPAGECRM_GETEXTERNALREMARK="/onepagecrm/getexternalremarks";
    String ONEPAGECRM_STORERMLOG="/onepagecrm/storeRMLog";
    String ONEPAGECRM_POSTREMARKS="/onepagecrm/postremarksv2";
    String ONEPAGECRM_SETCRMAGENT="/onepagecrm/setCrmAgents";
    String ALLOCATIONSERVICES_POSTPDOFFICERCRON="/allocation/post-pd-officer-cron";
    String ALLOCATIONSERVICES_SANCTIONDOCKOFFICERCRON="/allocation/sanction-doc-officer-cron";
    String ALLOCATIONSERVICES_PDOFFICER="/allocation/pd-officer";
    String ALLOCATIONSERVICES_TEAMEMPLOYEE="allocation/team-employee";
    String GSTSERVICE="/gstin/iris/getGstDetails/{case_code}";
    String EMANDATESERVICE_STATUS="/emandateflow/e-mandate/status/{case_code}";
    String EMANDATESERVICE_HEALTH="/emandateflow/e-mandate/health";
    String EMANDATESERVICE_CREATEPHYSICALMANDATE="/emandateflow/e-mandate/create/physical";
    String ALLOCATIONSERVICE_ROUNDROBIN="/allocation/allocate-lead/roundRobin";
    String ALLOCATIONSERVICE_ROUNDROBINCRON="/allocation/lead-allocation-roundrobin-cron";
    String ALLOCATIONSERVICE_ROUNDROBINCRONCRM="/allocation/lead-allocation-roundrobin-cron/:CRM";
    String EMANDATESERVICE_BANKELIGIBILITY="/emandateflow/v1/e-mandate/bank-eligibility";
    String EMANDATESERVICE_CREATEEMANDATE="/emandateflow/e-mandate/create/eMandate";
    String EMANDATESERVICE_SETMANDATETYPE="/emandateflow/e-mandate/callback-eMandate";
    String UNIFIEDDEDUPECHECK_DEDUPV1="/unified/caseapplicant/{MobileNo}/dedupecheck";
    String UNIFIEDDEDUPECHECK_DEDUPV2="/unified/v2/caseapplicant/{MobileNo}/dedupecheck";
    String PICKUPSERVICE_FETCHAGENCIES="/pickup/v1/agencies";
    String PICKUPSERVICE_SERVICEABLEAGENCIES="/pickup/v1/agencies";
    String PICKUPSERVICE_ADDRESSSERVICEABLEAGENCIES="/pickup/v1/agencies/config";
    String PICKUPSERVICE_FETCHDOCUMENTS="/pickup/v1/documents";
    String PICKUPSERVICE_FETCHPENDINGDOCUMENTS="/pickup/v1/documents/pending";
    String PICKUPSERVICE_STATUSES="/pickup/v1/statuses";
    String PICKUPSERVICE_caseDETAILS="/pickup/v1/caseDetails";
    String PICKUPSERVICE_FETCHTRACKINGDETAIL= "/pickup/v1/orders/{orderNo}";
    String PICKUPSERVICE_ELIGIBILITY = "/pickup/v1/documents/eligibility";
    String PICKUPSERVICE_ORDER="/pickup/v1/orders/customer/{case_code}";
    String PICKUPSERVICE_REQUEST="/pickup/v1/pickup/request";
    String DOCUMENTUPLOAD ="/documentservice/";
    String DOCUMENTPENDING="/documentservice/pending";
    String DOCUMENTPENDINGV1= "/documentservice/v1/pending";
    String DOCUMENTPENDINGHARDCOPY="/documentservice/pending/hardcopy/{case_code}";
    String DOCUMENTIGNORE= "/documentservice/pending/ignore";
    String DOCUMENTPENDINGSUMMARY="/documentservice/pending/summary";
    String DOCUMENTBULKUPLOAD = "/documentservice/bulk-upload";
    String DOCUMENTGETUNVERIFIED = "/documentservice/unverified";
    String DOCUMENTBUCKETMOVEPUT="/documentservice/doc/{UnverifiedCode_1}";
    String DOCUMENTGETVERIFIED = "/documentservice/v1/verified-documents";
    String DOCUMENTGETDELETED = "/documentservice/deleted";
    String DOCUMENTCLONNING = "/documentservice/services/case/clone";
    String DOCUMENTREALLOCATE = "/documentservice/services/case/reallocate";
    String DOCUMENTCONFIG = "/documentservice/config";
    String DOCUMENTCONFIGV1 = "/documentservice/v1/config";
    String DOCUMENTLOOKUP = "/documentservice/lookup";
    String DOCUMENTUPLOADRAW = "/documentservice/raw";
    String DOCUMENTMAP = "/documentservice/map";
    String DOCUMENTREQUIRED = "/documentservice/required";
    String DOCUMENTREQUIREDBULK = "/documentservice/required/bulk";
    String AMAZONINTEGRATION_INQUIRETESTOFFER ="amazonv2/inquireTestOffer";
    String PARTNERBACKEND_BUSINESSDETAILS="/partner/v1/case-application/{case_code}/business-details";
    String AMAZONINTEGRATION_TESTCREATEOFFER="/amazonv2/testCreateOffer";
    String MILESTONE_AUTO_DISBURSEMENT="/milestone/v1/case-application/{case_code}/milestones/AUTO_DISBURSEMENT_MILESTONE";
    String MILESTONE_AUTO_DISBURSEMENT_CHECKPOINTS="/milestone/v1/case-application/{case_code}/milestones/AUTO_DISBURSEMENT_MILESTONE/checkpoints";
    String POSTSANCTIONCOMMUNICATION_KFSDOWNLOAD="/psc/case/{case_code}/kfs/download";
    String SHARELEAD_CHECKPOINTS="/milestone/v1/case-application/{case_code}/milestones/{milestone_code}/checkpoints";
    String SHARELEAD_MILESTONE="/milestone/v1/case-application/{case_code}/milestones/{milestone_code}";
    String SHARELEAD_SHARELEAD="/epimoney/api/share_lead";
    String SHARELEAD_COLENDINGSTATUS="/v2/lead/colender/7/status";
    String POSTSANCTIONCOMMUNICATION_NOTEDOWNLOAD = "/psc/sanction/download";
    String ELIGIBILITY_FINALELIGIBILITY = "/eligibility/v2";
    String SHARELEAD_UPDATEFIELD = "/applicationstatus/api/updateField";
    String SHARELEAD_UPDATEIPSTATUS= "/los/application/updateIPStatus"; 
    String PARTNERINTEGRATION_EVALUATECHECKPOINT= "/state/v1/case/state";
    String POSTSANCTIONCOMMUNICATION_SENDSANCTIONV2FLOW="/psc/v2/sanction/{case_code}/send";
    String POSTSANCTIONCOMMUNICATION_FETCHTEMPLETEIDANDVERSIONID="/psc/fetchtemplates/{case_code}";
    String AUTOREJECT_APPLICATION="/autoreject/application";
    String PARTNERINTEGRATION_CALLBACK="/lms/v1/case-application/callback/approval";
    String PARTNERINTEGRATION_INITIATEAGREMENT="/c2w/v2/document/sign/init";
    String PARTNERINTEGRATION_DOCUMENTSIGN="/c2w/v2/document/sign/";
    String DIGILOCKER_SAVE="/digilocker/documents/save";
    String DIGILOCKER_FETCH="/digilocker/documents/fetch";
    String DOCUMENTSERVICE_PENDING="/documentservice/pending?case_code={case_code}";
    String UTILITY_MASTER_CIBIL_ACCOUNT_TYPE="/utility/master-cibil-account-types";
    String UTILITY_LOOKUPS="/utility/lookups";
    String UTILITY_STATES_AND_CITIES="/utility/states-and-cities";
    String UTILITY_POST_SANCTION_STATUSES="/utility/post-sanction-statuses";
    String UTILITY_EXPERIMENT_NAMES_OF_caseS="utility/case/:caseCode/experiment-names";
    String case_OFFERS="https://example.invalid";
    String PARTNER_LIST="https://example.invalid";
    String APPLICATION_TAGS="https://example.invalid";
    String UPDATE_STATEMENT="/app-bank/v1/banking/update-statement";
    String GET_BANKING_PERIOD="/app-bank/v1/banking/period";
    String GET_SUMMARY_DATA="/corebanking/v1/parsing/{case_code}/summary?summaryId={summaryId}";
    String UPDATE_ACCOUNT="/corebanking/v1/parsing/metadata/:identifier";
    String AA_DATA="/coredatalayer/data-connectors/v1/aa/vendors/setu/sessions/{session_id}";
    String FETCH_LIST_PARTNER="/utility/partners-list?cjp_link_disabled={cjp_link_disabled}";
    String CJP_Link_With_Associated_Partner="/partner/generate-cjp-url";
    String CDN_upload="/utility/cdn-upload";
    String CIBIL_APPLICANT="/bureau-app-layer/v2/bureau/getCibil?async=false&type=Applicant&force=true"; 
    String DIALERLOGIN="/api/dialerLogin";
    String OPC_TOKEN="/api/opc/token/";
    String CREATE_LMS_CLIENT="/los/createLMSClientAndApplication";
    String SANCTION_SEND="/psc/v2/sanction/";
    String ADD_PD="personaldiscussion/pdlist/add";
    String GET_STATUS="/state/v2/case/{case_code}";
    String UPDATE_STATUS="/los/application/updateIPStatus";
    String UPDATE_case_STATUS="/applicationstatus/api/case/{case_code}/status";
    String VERIFY_DOC="/documentservice/doc/";
    String CHECK_POLICY="/policy/check-policies/";
    String FETCH_PD="/personaldiscussion/pd-details/";
    String POLICY_LOG="/policy/policy-log/";
    String FETCH_CIBIL="/bureau-app-layer/v2/bureau/getCibil?async=false&type=Applicant&force=true&mode=HARD_CIBIL_PULL";
    String MILESTONE="/milestone/v1/case-application/{casecode}/milestones/sample_LEAD_SHARE/checkpoints";
    String case_OFFER="/offers/v1/case-application/{case_code}/case/offers";
    String REDIRECT_URI="/partner/redirectlink";
    String SEND_OTP="customer/customer/common/sms/send";
    String CONFIRM_OTP="customer/customer/common/sms/v1/verify";
    String BIFROST_GET="/middleware/v1/lead/originator/";
    String FORCE_PARSE="/app-bank/v1/banking/parse/";
    String FUZZYNAME_FLAG="/app-bank/v1/banking/name-match/update";
    String DOCUMENTSERVICE = "/documentservice/{case_code}/classification/{document_code}";
    String REPAYMENT_DETAIL="/lms/repayment-details-client/{client_code}";
    String CIBIL_MOCK="/bureau-app-layer/v2/bureau/getCibil?async=false&type=Applicant&force=true&mode=HARD_CIBIL_PULL"; 
    String DISBURSAL_CALLBACK="/utility/callback/disbursal";
    String LMSAPPROVE="/lms/v1/approved/case/";
    String LMSAPPROVESAVING="/lms/v1/approved/savingsaccounts/";
    String APR="/api/caseApplication/getApprovedDetails";
    String SANCTIONSTATUS ="/psc/v2/sanctionstatus/";
    String UPDATELEAD="/los/postsanction/updatecurrentstatus/";
    String BRE="/scoringservice/bre/epimoney/";
    String FETCHBRE="/scoringservice/bre/epimoney?case_code=";
    String GSTIN = "/gst/iris/getGstDetails/";
    String COLLECTION="/epimoney/api/collection";
    String GUARANTOR_CIBIL_MOCK="/bureau-app-layer/v2/bureau/getCibil?async=false&type=Guarantors&force=true&mode=HARD_CIBIL_PULL"; 
    String REPAYMENT_DETAIL_CLM="/epimoney/api/case/{casecode}/disbursement/repayment_schedule";
    String AGREEMENT_CLM="/middleware/v2/lead/originator/{casecode}/colender/{colender_id}/share/pool/agreement";
    String POSTPOLICY="/applicationlayer/v1/post-disbursement/policy";
    String GENERATECAM="/applicationlayer/v1/documents/generate";
    String MARK_STATEMENT="/bsa/markImpStatement/";
    String PRODUCT_LIST="/onepagecrm/industryclassificationproductlist";
    String BULK_LEAD_CREATION = "/applicationlayer/v1/api/caseApplication/bulkLeadCreation/{case_code}";
    String CHECK_case_TYPE = "/applicationlayer/v1/api/caseApplication/{case_code}/checkcaseType";
    String FILE_UPLOAD_STATUS = "/applicationlayer/v1/caseAppData/fileUploadStatus/{partner_code}";
    String case_APPDATA = "/applicationlayer/v1/caseAppData/{case_code}";
    String CIBILPULL = "/bureau-app-layer/v2/bureau/getCibil?async=false&type=Applicant&force=true&mode=HARD_CIBIL_PULL/";
    String PARTNER_CIBIL = "/bureau-app-layer/v2/bureau/getCibil?async=false&type=Partners&force=true&mode=HARD_CIBIL_PULL";
    String CKYC_SERVICE = "/ckyc/v1/ckyc";

}
